name: TheSenate
version: '${project.version}'
main: com.senate.thesenate.Main
api-version: 1.17
commands:
  SetItemDamage:
    description: Set the chance of item taking damage
    usage: /<command> <item> <percent chance of item taking damage>
    permissions: senate.setitemdamage
  Debug:
    description: enabled/disable debug mode
    usage: /<command> <true|false>
    permissions: senate.debug
  Cords:
    description: save and view cordinates
    usage: /<command> <list|add|remove|name> [name] [X] [Y] [Z]
    permissions: senate.cords