name: CustomeItemDamage
main: main.java.Hook
version: 1.0
api-version: 1.17.1
commands:
  reduce_item_damage:
    description: Set the chance of item taking damage
permissions:
  reduce_item_damage:
    default: true